import { Container, Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import AuthProvider from "./auth/Provider";
import "./globals.css";
import NavBar from "./NavBar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const poppins = Poppins({ subsets: ["latin-ext"], weight: ['400', '800'], });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Theme appearance="light" >
            <NavBar />
            <main className="p-5" >
              <Container>
                {children}
              </Container>
            </main>
            {/* <ThemePanel /> --> Use to choose theme style */}
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
